username = "my-user"
repository = "https://github.com/my-org/my-repo"

[[labelRule]]
  [labelRule.create]
  name = "label1"
  description = "a cool label"
  hexColor = "#000000"

[[labelRule]]
  [labelRule.override]
  old = "old label name"
  new = "new label name"

[[ignoredRepository]]
repo = "https://github.com/my-org/my-ignored-repo"

[[ignoredRepository]]
repo = "https://github.com/my-org/my-other-ignored-repo"
